---
title: "Student Project"
author: "Beatrice Magistro"
date: "10/10/2016"
output: pdf_document
---

Our research project investigates which individual factors are more likely to be associated with a Brexit vote. We will examine whether economic or cultural explanations are more likely to be associated with anti-EU stance. We will rely on two different datasets to test our hypotheses and we will also eventually use official data from the Referendum to check whether cross-regionally Brexit votes corresponded with the dependent variables, that try to measure the Brexit vote as close as possible.

The two datasets we will be using are the Eurobarometer and the European Social Survey. We will use the May 2015 Eurobarometer wave and the 2014 European Social Survey wave. The unit of analysis are individual respondents. The dependent variable of interest from the EB dataset is: "Better future outside of the EU"", which is a discrete variable that takes four possible values: Strongly agree (1), agree (2), disagree (3), strongly disagree (4). The dependent variable of interest from the ESS dataset is:  "Now thinking about the European Union, some say European unification should go further. Others say it has already gone too far. Using this card, what number on the scale best describes your position?" A lower score (e.g. 1) means "Unification already gone too far" and a higher score (e.g. 10) "Unification go further". 

The probability distribution that best describes our data are multinomial distributions in both datasets.Two assumptions of a multinomial distribution are that the trials it illustrates must be independent and the probability of each possible result must be constant. We do not think that any of these assumptions are violated by that data.

We believe that it would be appropriate to use MLE or ordinal logistic regression.

Our covariates of interest will be variables on the sujective and objective feelings towards the state of the economy in a country, feelings towards immigration, stances towards globalization and we will use socio-demographic controls such as age, education, gender and region.

```{r, echo=FALSE}
EB <- read_dta("EB.dta")
varnames <- c('unemplratecorrect','inflratecorrect', 'growthcorrect', 'econ2correct'
)
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(9),
                     NA, EB[[i]])
}

varnames <- c('finaexp', 'econexp', 'inflratecompared2013'
              )
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(4, 8, 9),
                     NA, EB[[i]])
}

varnames <- c('situationatecon', 'situationeuecon', 'finasituation',
              'feeleuimmigration', 'feelnoneuimmigration',
              'betteroutsideeu', 'crisisreducepublicdebt','crisispublicdebtnopriority',
              'eusufficientpowers','crisisprivatesectorjobs', 'crisispublicinvestment',
              'statspoldecisions', 'satisdmo', 'satisdeu', 'citizen','stateintervenestoomuch',
              'toomuchtolerance', 'immigrantscontribute'
              )
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(5, 6, 7, 8, 9),
                     NA, EB[[i]])
}

varnames <- c('trustnp', 'trustgov',
              'trusteu','heardep',
              'heardec', 'heardecb', 'trustep', 'trustec', 'trustecb',
              'euknownomemb', 'euknowswimemb', 'euknowepelect', 'statstrust')
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(3, 8, 9),
                     NA, EB[[i]])
}

varnames <- c('euimage', 'soclass', 'educrec5'
              )
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(6, 7, 8, 9),
                     NA, EB[[i]])
}


varnames <- c('unemplrate2014rec')
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(8, 99),
                     NA, EB[[i]])
}

varnames <- c('inflrate2014rec', 'growth2014rec')
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(9, 99),
                     NA, EB[[i]])
}

varnames <- c('unemplrate2014', 'inflrate2014', 'growth2014')
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(99999, 999999),
                     NA, EB[[i]])
}

varnames <- c('married'
)
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(15, 97),
                     NA, EB[[i]])
}

varnames <- c('educ'
)
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(0, 97, 98, 99),
                     NA, EB[[i]])
}

varnames <- c('lrs', 'educrec11'
)
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(97, 98),
                     NA, EB[[i]])
}

varnames <- c("regionBE",                  "regionFR",
              "regionNE",                   "regionDE",                   "regionIT",
              "regionLU",                   "regionDK",                   "regionIE",
              "regionUK",                   "regionGR",                   "regionES",
             "regionPT",                   "regionFI",                   "regionSE",
              "regionAU",                   "regionCY",                   "allregions",
              "regionCZ",                   "regionEE",                   "regionHU",
               "regionLV",                   "regionLT",                   "regionPL",
             "regionSK",                   "regionSI",                   "regionBG",
             "regionRO",                   "regionTR",                   "regionHR",
               "regionTCC",                  "regionMK",                   "regionRS",
              "regioneME",                  "regionAL"
)
for (i in varnames) {
  EB[[i]] <- ifelse(EB[[i]] %in% c(99),
                     NA, EB[[i]])
}

EB$age_gr <- cut(EB$age,
                  breaks = c(14, 25, 35, 45, 55, 65, 100),
                  labels = c("15-24", "25-34","35-44","45-54",
                             "55-64","65+"),
                  right = FALSE)

EB$country <- recode(EB$country, "'DE-E' = 'DE'; 'DE-W' = 'DE';
                       'GB-GBN' = 'UK'; 'GB-NIR' = 'UK'")
UK <- filter(EB, country=='UK')
ggplot(UK, aes(betteroutsideeu)) + geom_bar() + labs(x="Better future outside of the EU")
```


